api_platform:
    title: 'e-OSVČ'
    version: '0.0.0'
    mapping:
        paths:
            - '%kernel.project_dir%/config/api'
    formats:
        json:
            mime_types:
                - 'application/json'
        html:
            mime_types:
                - 'text/html'
    patch_formats:
        json:
            - 'application/merge-patch+json'
    swagger:
        versions:
            - 3
    collection:
        pagination:
            enabled: false
