security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    role_hierarchy:
        !php/const App\Entity\User::ROLE_USER: ~
        !php/const App\Entity\User::ROLE_ADMIN: !php/const App\Entity\User::ROLE_USER
        !php/const App\Entity\User::ROLE_SUPER_ADMIN: !php/const App\Entity\User::ROLE_ADMIN

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /auth
                username_path: username
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - path: ^/$
          roles:
              - IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/users$
          methods: [POST]
          roles:
            - IS_AUTHENTICATED_ANONYMOUSLY
        - path: ^/users
          roles:
              - !php/const App\Entity\User::ROLE_USER

