framework:
    validation:
        enabled: true
        email_validation_mode: html5
        mapping:
            paths:
                - '%kernel.project_dir%/config/validation/'
        auto_mapping:
            App\Entity\: []
