App\Entity\Client:
  attributes:
    id:
      groups:
        - client_out_list
        - client_out_detail
        - invoice_out_list
        - invoice_out_detail
        - project_out_list
        - project_out_detail
    name:
      groups:
        - client_out_list
        - client_out_detail
        - client_in
        - project_out_list
        - project_out_detail
    owner:
      groups:
        - client_out_detail
