App\Entity\Client:
  attributes:
    id:
      groups:
        - client_out_list
        - client_out_detail
    name:
      groups:
        - client_out_list
        - client_out_detail
        - client_in
    owner:
      groups:
        - client_out_detail
