App\Entity\InvoiceUserInfo:
  attributes:
    id:
      groups:
        - invoice_out_list
        - invoice_out_detail
    firstName:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    lastName:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    street:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    city:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    postalCode:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    cidNumber:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    taxNumber:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    bankAccount:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
