App\Entity\Invoice:
  attributes:
    id:
      groups:
        - invoice_out_list
        - invoice_out_detail
    invoiceIdentifier:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    invoiceDate:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    invoiceDueDate:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    invoicePaymentDate:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    paymentVariableSymbol:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    userInfo:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    clientInfo:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    projectInfoItems:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    invoiceItems:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - invoice_in
    timeRecords:
      groups:
        - invoice_out_detail
    owner:
      groups:
        - invoice_out_detail
