App\Entity\Project:
  attributes:
    id:
      groups:
        - invoice_out_list
        - invoice_out_detail
        - project_out_list
        - project_out_detail
    name:
      groups:
        - project_out_list
        - project_out_detail
        - project_in
    client:
      groups:
        - project_out_list
        - project_out_detail
        - project_in
    owner:
      groups:
        - project_out_detail
