App\Entity\SocialInsurance:
  attributes:
    id:
      groups:
        - social_insurance_out_list
        - social_insurance_out_detail
    date:
      groups:
        - social_insurance_out_list
        - social_insurance_out_detail
        - social_insurance_in
    amount:
      groups:
        - social_insurance_out_list
        - social_insurance_out_detail
        - social_insurance_in
    variant:
      groups:
        - social_insurance_out_list
        - social_insurance_out_detail
        - social_insurance_in
    note:
      groups:
        - social_insurance_out_list
        - social_insurance_out_detail
        - social_insurance_in
    owner:
      groups:
        - social_insurance_out_detail
