App\Entity\TimeRecord:
  attributes:
    id:
      groups:
        - invoice_out_detail
        - time_record_out_list
        - time_record_out_detail
    startDateTime:
      groups:
        - invoice_out_detail
        - time_record_out_list
        - time_record_out_detail
        - time_record_in
    endDateTime:
      groups:
        - invoice_out_detail
        - time_record_out_list
        - time_record_out_detail
        - time_record_in
    note:
      groups:
        - invoice_out_detail
        - time_record_out_list
        - time_record_out_detail
        - time_record_in
    project:
      groups:
        - invoice_out_detail
        - time_record_out_list
        - time_record_out_detail
        - time_record_in
    owner:
      groups:
        - time_record_out_detail
