App\Entity\User:
  attributes:
    id:
      groups:
        - client_out_detail
        - health_insurance_out_detail
        - invoice_out_list
        - invoice_out_detail
        - project_out_detail
        - sickness_insurance_out_detail
        - social_insurance_out_detail
        - user_out_list
        - user_out_detail
    firstName:
      groups:
        - user_out_list
        - user_out_detail
        - user_in
    lastName:
      groups:
        - user_out_list
        - user_out_detail
        - user_in
    street:
      groups:
        - user_out_detail
        - user_in
    city:
      groups:
        - user_out_detail
        - user_in
    postalCode:
      groups:
        - user_out_detail
        - user_in
    cidNumber:
      groups:
        - user_out_detail
        - user_in
    taxNumber:
      groups:
        - user_out_detail
        - user_in
    bankAccount:
      groups:
        - user_out_detail
        - user_in
    username:
      groups:
        - user_out_list
        - user_out_detail
        - auth_in
        - user_in
    email:
      groups:
        - user_out_list
        - user_out_detail
        - user_in
    plainPassword:
      groups:
        - user_in
    isActive:
      groups:
        - user_out_list
        - user_out_detail
    roles:
      groups:
        - user_out_list
        - user_out_detail
    token:
      groups:
        - auth_detail_out
