App\Entity\Client:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 64

    street:
      - NotBlank: ~
      - Length:
          max: 128

    city:
      - NotBlank: ~
      - Length:
          max: 128

    postalCode:
      - NotBlank: ~
      - Range:
          min: 1
          max: 99999

    cidNumber:
      - Range:
          min: 0

    taxNumber:
      - Range:
          min: 0

    contactEmail:
      - Length:
          max: 128
      - Email: ~

    contactPhoneNumber:
      - Length:
          max: 32

    owner:
      - NotBlank: ~
