App\Entity\InvoiceUserInfo:
  properties:
    firstName:
      - NotBlank: ~
      - Length:
          max: 32

    lastName:
      - NotBlank: ~
      - Length:
          max: 32

    street:
      - NotBlank: ~
      - Length:
          max: 128

    city:
      - NotBlank: ~
      - Length:
          max: 128

    postalCode:
      - NotBlank: ~
      - Range:
          min: 1
          max: 99999

    cidNumber:
      - NotBlank: ~
      - Range:
          min: 0

    taxNumber:
      - Range:
          min: 0

    bankAccount:
      - NotBlank: ~
      - Length:
          max: 64
