App\Entity\Invoice:
  properties:
    invoiceIdentifier:
      - NotBlank: ~
      - Length:
          max: 32

    invoiceDate:
      - NotBlank: ~

    invoiceDueDate:
      - NotBlank: ~

    paymentVariableSymbol:
      - NotBlank: ~
      - Range:
          min: 1
          max: 9999999999

    userInfo:
      - NotBlank: ~
      - Valid: ~

    clientInfo:
      - NotBlank: ~
      - Valid: ~

    projectInfoItems:
      - NotBlank: ~
      - Count:
          min: 1
      - Valid: ~

    invoiceItems:
      - NotBlank: ~
      - Count:
          min: 1
      - Valid: ~

    owner:
      - NotBlank: ~
