App\Entity\InvoiceClientInfo:
  properties:
    name:
      - NotBlank: ~
      - Length:
          max: 64

    street:
      - NotBlank: ~
      - Length:
          max: 128

    city:
      - NotBlank: ~
      - Length:
          max: 128

    postalCode:
      - NotBlank: ~
      - Range:
          min: 1
          max: 99999

    cidNumber:
      - GreaterThan:
          value: 0

    taxNumber:
      - Length:
          max: 32

    original:
      - NotBlank: ~
