App\Entity\Client:
  type: entity
  table: client

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    name:
      type: string
      length: 64

    street:
      type: string
      length: 128

    city:
      type: string
      length: 128

    postalCode:
      type: integer

    cidNumber:
      type: integer
      nullable: true

    taxNumber:
      type: integer
      nullable: true

    contactEmail:
      type: string
      length: 128
      nullable: true

    contactPhoneNumber:
      type: string
      length: 32
      nullable: true

  manyToOne:
    owner:
      targetEntity: App\Entity\User
      inversedBy: clients
      joinColumn:
        name: owner_id
        referencedColumnName: id
        nullable: false

  oneToMany:
    projects:
      targetEntity: App\Entity\Project
      mappedBy: client
