App\Entity\InvoiceItem:
  type: entity
  table: invoice_item

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    quantity:
      type: integer

    pricePerQuantityUnit:
      type: float

    quantityUnit:
      type: string
      length: 8
      nullable: true

    note:
      type: text

  manyToOne:
    invoice:
      targetEntity: App\Entity\Invoice
      inversedBy: invoiceItems
      joinColumn:
        name: invoice_id
        referencedColumnName: id
        nullable: false
        onDelete: CASCADE
