App\Entity\InvoiceUserInfo:
  type: entity
  table: invoice_user_info

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    firstName:
      type: string
      length: 32

    lastName:
      type: string
      length: 32

    street:
      type: string
      length: 128

    city:
      type: string
      length: 128

    postalCode:
      type: integer

    cidNumber:
      type: integer

    taxNumber:
      type: integer
      nullable: true

    bankAccount:
      type: string
      length: 64

  oneToOne:
    invoice:
      targetEntity: App\Entity\Invoice
      mappedBy: userInfo
