App\Entity\InvoiceClientInfo:
  type: entity
  table: invoice_client_info

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    name:
      type: string
      length: 64

    street:
      type: string
      length: 128

    city:
      type: string
      length: 128

    postalCode:
      type: integer

    cidNumber:
      type: integer
      nullable: true

    taxNumber:
      type: string
      length: 32
      nullable: true

  oneToOne:
    invoice:
      targetEntity: App\Entity\Invoice
      mappedBy: clientInfo

  manyToOne:
    original:
      targetEntity: App\Entity\Client
      joinColumn:
        name: original_id
        referencedColumnName: id
        nullable: true
