App\Entity\InvoiceClientInfo:
  type: entity
  table: invoice_client_info

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    name:
      type: string
      length: 64

  oneToOne:
    invoice:
      targetEntity: App\Entity\Invoice
      mappedBy: clientInfo

  manyToOne:
    original:
      targetEntity: App\Entity\Client
      joinColumn:
        name: original_id
        referencedColumnName: id
        nullable: true
