App\Entity\Project:
  type: entity
  table: project

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    name:
      type: string
      length: 64

  manyToOne:
    client:
      targetEntity: App\Entity\Client
      inversedBy: projects
      joinColumn:
        name: client_id
        referencedColumnName: id
        nullable: false
    owner:
      targetEntity: App\Entity\User
      inversedBy: projects
      joinColumn:
        name: owner_id
        referencedColumnName: id
        nullable: false
