App\Entity\User:
  type: entity
  table: app_user

  id:
    id:
      type: integer
      generator: { strategy: IDENTITY }

  fields:
    firstName:
      type: string
      length: 32

    lastName:
      type: string
      length: 32

    street:
      type: string
      length: 128

    city:
      type: string
      length: 128

    postalCode:
      type: integer

    cidNumber:
      type: integer

    taxNumber:
      type: integer
      nullable: true

    bankAccount:
      type: string
      length: 64

    email:
      type: string
      length: 64
      unique: true

    username:
      type: string
      length: 64
      unique: true

    password:
      type: text

    isActive:
      type: boolean

    roles:
      type: json

  oneToMany:
    clients:
      targetEntity: App\Entity\Client
      mappedBy: owner

    projects:
      targetEntity: App\Entity\Project
      mappedBy: owner

    invoices:
      targetEntity: App\Entity\Invoice
      mappedBy: owner

    socialInsurances:
      targetEntity: App\Entity\SocialInsurance
      mappedBy: owner
