App\Entity\Client:
  attributes:
    order:
      name: ASC
  collectionOperations:
    post:
      method: POST
      normalization_context:
        groups:
          - client_out_detail
      denormalization_context:
        groups:
          - client_in
      security_post_denormalize: "is_granted('ROLE_USER')"
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - client_out_detail
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    put:
      method: PUT
      normalization_context:
        groups:
          - client_out_detail
      denormalization_context:
        groups:
          - client_in
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    delete:
      method: DELETE
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
  subresourceOperations:
    api_users_clients_get_subresource:
      method: GET
      normalization_context:
        groups:
          - client_out_list
      security: "is_granted('ROLE_USER')" # TODO: Fix security rule to check owner
