App\Entity\SicknessInsurance:
  attributes:
    order:
      date: DESC
  collectionOperations:
    post:
      method: POST
      normalization_context:
        groups:
          - sickness_insurance_out_detail
      denormalization_context:
        groups:
          - sickness_insurance_in
      security_post_denormalize: "is_granted('ROLE_USER')"
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - sickness_insurance_out_detail
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    put:
      method: PUT
      normalization_context:
        groups:
          - sickness_insurance_out_detail
      denormalization_context:
        groups:
          - sickness_insurance_in
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    delete:
      method: DELETE
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
  subresourceOperations:
    api_users_sickness_insurances_get_subresource:
      method: GET
      normalization_context:
        groups:
          - sickness_insurance_out_list
