App\Entity\Tax:
  attributes:
    order:
      date: DESC
  collectionOperations:
    post:
      method: POST
      normalization_context:
        groups:
          - tax_out_detail
      denormalization_context:
        groups:
          - tax_in
      security_post_denormalize: "is_granted('ROLE_USER')"
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - tax_out_detail
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    put:
      method: PUT
      normalization_context:
        groups:
          - tax_out_detail
      denormalization_context:
        groups:
          - tax_in
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    delete:
      method: DELETE
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
  subresourceOperations:
    api_users_taxes_get_subresource:
      method: GET
      normalization_context:
        groups:
          - tax_out_list
      security: "is_granted('ROLE_USER')" # TODO: Fix security rule to check owner
