App\Entity\TimeRecord:
  attributes:
    order:
      startDateTime: DESC
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - time_record_out_list
      security_post_denormalize: "is_granted('ROLE_USER')"
      filters:
        - 'time_records.date_filter'
        - 'time_records.search_filter'
        - 'time_records.in_or_null_filter'
    post:
      method: POST
      normalization_context:
        groups:
          - time_record_out_detail
      denormalization_context:
        groups:
          - time_record_in
      security_post_denormalize: "is_granted('ROLE_USER')"
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - time_record_out_detail
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    put:
      method: PUT
      normalization_context:
        groups:
          - time_record_out_detail
      denormalization_context:
        groups:
          - time_record_in
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
    delete:
      method: DELETE
      security: "is_granted('ROLE_USER') and object.getOwner() == user"
  subresourceOperations:
    api_users_time_records_get_subresource:
      method: GET
      normalization_context:
        groups:
          - time_record_out_list
