App\Entity\User:
  collectionOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - user_out_list
    post:
      method: POST
      normalization_context:
        groups:
          - user_out_detail
      denormalization_context:
        groups:
          - user_in
  itemOperations:
    get:
      method: GET
      normalization_context:
        groups:
          - user_out_detail
    put:
      method: PUT
      normalization_context:
        groups:
          - user_out_detail
      denormalization_context:
        groups:
          - user_in
    delete:
      method: DELETE
  properties:
    clients:
      subresource:
        resourceClass: 'App\Entity\Client'
        collection: true
    projects:
      subresource:
        resourceClass: 'App\Entity\Project'
        collection: true
